In [18]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [ ]:
driver = webdriver.Chrome()
books = []
ratings = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
for page in range(1, 6):
    driver.get("https://books.toscrape.com/catalogue/page-" + str(page) + ".html")

    items = driver.find_elements(By.XPATH, "//article[@class='product_pod']")

    for item in items:

        link = item.find_element(By.XPATH, ".//h3/a")
        title = link.get_attribute("title")
        url = link.get_attribute("href")

        price_text = item.find_element(By.XPATH, ".//p[@class='price_color']").text
        price = float(price_text.replace("£", ""))

        rating_class = item.find_element(By.XPATH, ".//p[contains(@class,'star-rating')]").get_attribute("class")
        rating = ratings[rating_class.split()[1]]

        stock = item.find_element(By.XPATH, ".//p[@class='instock availability']").text
    
        books.append({ "title": title,"price": price, "rating": rating, "in_stock": stock, "url": url })

driver.quit()

In [ ]:
df = pd.DataFrame(books)
df.to_csv("books.csv", index=False)
print("Saved", len(df), "books")

Saved 100 books

In [21]:
df

,title,price,rating,in_stock,url
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...
...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,19.92,2,In stock,https://books.toscrape.com/catalogue/lumberjan...
96,"Layered: Baking, Building, and Styling Spectac...",40.11,1,In stock,https://books.toscrape.com/catalogue/layered-b...
97,Judo: Seven Steps to Black Belt (an Introducto...,53.90,2,In stock,https://books.toscrape.com/catalogue/judo-seve...
98,Join,35.67,5,In stock,https://books.toscrape.com/catalogue/join_902/...
99,In the Country We Love: My Family Divided,22.00,4,In stock,https://books.toscrape.com/catalogue/in-the-co...

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     100 non-null    str
 1   price     100 non-null    float64
 2   rating    100 non-null    int64
 3   in_stock  100 non-null    str
 4   url       100 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 4.0 KB

In [24]:
df.describe()

            price      rating
count  100.000000  100.000000
mean    34.560700    2.930000
std     14.638531    1.423149
min     10.160000    1.000000
25%     19.897500    2.000000
50%     34.775000    3.000000
75%     47.967500    4.000000
max     58.110000    5.000000